Faradise.Design.Admin/Controllers/AdminARProductController.cs
using Faradise.Design.Admin.Services;
using Faradise.Design.Controllers.API.Models.Admin;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faradise.Design.Admin.Controllers
{
    [Route("ar-product")]
    [ResponseCache(NoStore = true)]
    public class AdminARProductController : Controller
    {
        private HttpService _http = null;

        public AdminARProductController(HttpService http)
        {
            _http = http;
        }

        [HttpGet("ar-product/{id}")]
        public async Task<IActionResult> ARProduct(int id)
        {
            var product = await _http.Get<AdminARProductModel>("api/admin/marketplace/ar/get-ar-product-info", new Dictionary<string, string> { { "arProductId", id.ToString() } });
            if (product.Result != null)
                return View(product.Result);
            return RedirectToAction("ARProductList");
        }

        [HttpPost("set-ar-to-product")]
        public async Task<IActionResult> SetArToProduct(int? productId, int arId)
        {
            var result = await _http.Post<bool>("api/admin/marketplace/ar/set-product-to-ar", new SetArProductModel { ArProductId = arId, ProductId = productId });
            return RedirectToAction("ARProduct", new { id = arId });
        }

        [HttpGet("ar-product-list")]
        public async Task<IActionResult> ARProductList()
        {
            var products = await _http.Get<AdminARProductShortModel[]>("api/admin/marketplace/ar/get-products");
            return View(products.Result);
        }

        [HttpGet("parse-csv")]
        public async Task<IActionResult> ParseCSV()
        {
            await _http.Get<AdminARProductShortModel[]>("api/admin/marketplace/parsing");
            return RedirectToAction("ARProductList");
        }
    }
}

Faradise.Design.Admin/Views/AdminARProduct/ARProduct.cshtml
@model AdminARProductModel

@{
    ViewData["Title"] = "Информация";
}

<style type="text/css">
    .carousel-control-prev-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
    }

    .carousel-control-next-icon {
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23000' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
    }
</style>

<div class="container-fluid m-1">
    <div class="card">
        <h5 class="card-header">@Model.Name</h5>
        <br />

        <div id="carousel" class="carousel slide" data-ride="carousel" style="width: 360px;">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img style="width: 100%; max-height: 300px; object-fit: contain" class="d-block w-100" src="@Model.Render" alt="@Model.Render">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Faradise ID</b></div>
            <div class="col-lg-2">@Model.FaradiseProductId</div>
        </div>
        <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Артикуль</b></div>
            <div class="col-lg-2">@Model.VendorCode</div>
        </div>
        <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Плоскость</b></div>
            @if (@Model.Vertiacal)
        {
            <div class="col-lg-2">Горизонтальная</div>
    }
    else
    {
        <div class="col-lg-2">Вертикальная</div>
}
        </div>
        <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Цвет</b></div>
            <div class="col-lg-2">@Model.Color</div>
        </div>
        <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Id цвета Faradise</b></div>
            <div class="col-lg-2">@Model.FaradiseColorId</div>
        </div>

        <br />

        <div class="card">
            <h5 class="card-header">Связь с нашей базой</h5>
            <br />
            <div class="card card-body">
            <div class="row p-1 m-2">
            <div class="col-lg-2"><b>ProductID</b></div>
            @if (@Model.ProductId.HasValue)
            {
                <div class="col-lg-2">@Model.ProductId</div>
            }
            else
            {
                <div class="col-lg-2">не задан</div>
            }
            @using (Html.BeginForm("SetArToProduct", "AdminARProduct", FormMethod.Post))
            {
            <input type="hidden" value="@Model.Id" name="arId" />
            <input type="number" name="productId" />
            <input type="submit" value="Изменить" />
            }
            </div>

            <div class="row p-1 m-2">
            <div class="col-lg-2"><b>Имя продукта</b></div>
            @if (!string.IsNullOrEmpty(Model.ProductName))
            {
                <div class="col-lg-2">@Model.ProductName</div>
            }
            else
            {
               <div class="col-lg-2">не задан</div>
            }
            </div>
            </div>
        </div>

        <br />
        @if (Model.IosSCN != null)
    {
        <a class="btn btn-info" data-toggle="collapse" href="#collapse_iosSCN" role="button" aria-expanded="false" aria-controls="collapse_iosSCN">
            Данные IOS + SCN
        </a>
        <div class="collapse" id="collapse_iosSCN">
            <h5 class="card-header">IOS + SCN</h5>
            <div class="card card-body">
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Модель</b></div>
                    <div class="col-lg-10">@Model.IosSCN.GeometryUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Diffuse</b></div>
                    <div class="col-lg-10">@Model.IosSCN.DiffuseUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Normal</b></div>
                    <div class="col-lg-10">@Model.IosSCN.NormalUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metalic</b></div>
                    <div class="col-lg-10">@Model.IosSCN.MetalicUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Roughness</b></div>
                    <div class="col-lg-10">@Model.IosSCN.RoughnessUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metallic Roughnes</b></div>
                    <div class="col-lg-10">@Model.IosSCN.MetallicRoughnessUrl</div>
                </div>
            </div>
        </div>
}

        <br />
        @if (Model.IosBFM != null)
    {
        <a class="btn btn-info" data-toggle="collapse" href="#collapse_iosBFM" role="button" aria-expanded="false" aria-controls="collapse_iosBFM">
            Данные IOS + BFM
        </a>
        <div class="collapse" id="collapse_iosBFM">
            <h5 class="card-header">IOS + BFM</h5>
            <div class="card card-body">
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Модель</b></div>
                    <div class="col-lg-10">@Model.IosBFM.GeometryUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Diffuse</b></div>
                    <div class="col-lg-10">@Model.IosBFM.DiffuseUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Normal</b></div>
                    <div class="col-lg-10">@Model.IosBFM.NormalUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metalic</b></div>
                    <div class="col-lg-10">@Model.IosBFM.MetalicUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Roughness</b></div>
                    <div class="col-lg-10">@Model.IosBFM.RoughnessUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metallic Roughnes</b></div>
                    <div class="col-lg-10">@Model.IosBFM.MetallicRoughnessUrl</div>
                </div>
            </div>
        </div>
}

        <br />
        @if (Model.AndroidBFM != null)
    {
        <a class="btn btn-info" data-toggle="collapse" href="#collapse_AndroidBFM" role="button" aria-expanded="false" aria-controls="collapse_AndroidBFM">
            Данные Adndroid + BFM
        </a>
        <div class="collapse" id="collapse_AndroidBFM">
            <h5 class="card-header">Android + BFM</h5>
            <div class="card card-body">
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Модель</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.GeometryUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Diffuse</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.DiffuseUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Normal</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.NormalUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metalic</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.MetalicUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Roughness</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.RoughnessUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metallic Roughnes</b></div>
                    <div class="col-lg-10">@Model.AndroidBFM.MetallicRoughnessUrl</div>
                </div>
            </div>
        </div>
}

        <br />
        @if (Model.AndroidSFB != null)
    {
        <a class="btn btn-info" data-toggle="collapse" href="#collapse_AndroidSFB" role="button" aria-expanded="false" aria-controls="collapse_AndroidSFB">
            Данные Adndroid + SFB
        </a>
        <div class="collapse" id="collapse_AndroidSFB">
            <h5 class="card-header">Android + SFB</h5>
            <div class="card card-body">
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Модель</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.GeometryUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Diffuse</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.DiffuseUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Normal</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.NormalUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metalic</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.MetalicUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Roughness</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.RoughnessUrl</div>
                </div>
                <div class="row p-1 m-2">
                    <div class="col-lg-2"><b>Metallic Roughnes</b></div>
                    <div class="col-lg-10">@Model.AndroidSFB.MetallicRoughnessUrl</div>
                </div>
            </div>
        </div>
}
    </div>
</div>

Faradise.Design.Admin/Views/AdminARProduct/ARProductList.cshtml
@model AdminARProductShortModel[]

@{
    ViewData["Title"] = "Список AR объектов";
}

<div class="row border rounded p-1 m-1 vertical-align">
    <div class="col-lg-3">
        <b>Всего : @Model.Length шт.</b>
    </div>
</div>

<div class="row border rounded p-1 m-1">
    @Html.ActionLink("Перезагрузить модели", "ParseCSV", "AdminARProduct", null, new { @class = "btn btn-outline-danger" })
</div>

<div class="row border rounded p-1 m-1 vertical-align">
    <div class="col-md-3 text-center">
        <b>Имя</b>
    </div>
    <div class="col-md-1 text-center">
        <b>Faradise ID</b>
    </div>
    <div class="col-md-2 text-center">
        <b>Цвет</b>
    </div>
    <div class="col-md-1 text-center">
        <b>Product ID</b>
    </div>
    <div class="col-md-3 text-center">
        <b>Имя продукта</b>
    </div>
    <div class="col-md-2 text-center">
        <b></b>
    </div>
</div>

@foreach (var m in Model)
{
    <div class="row border rounded p-1 m-1 vertical-align">
        <div class="col-md-3 text-center">
            <b>@m.FaradiseName</b>
        </div>
        <div class="col-md-1 text-center">
            <b>@m.FaradiseId</b>
        </div>
        <div class="col-md-2 text-center">
            @m.Color
        </div>
        @if (m.ProductId != null)
        {
            <div class="col-md-1 text-center">
                @m.ProductId
            </div>
            <div class="col-md-3 text-center">
                @m.ProductName
            </div>
        }
        else
        {
            <div class="col-md-1 text-center">
                не задан
            </div>
            <div class="col-md-3 text-center">
                не задан
            </div>
        }
        <div class="col-md-2 text-center align-self-end">
            @Html.ActionLink("открыть", "ARProduct", "AdminARProduct", new { id = m.Id }, new { @class = "btn btn-outline-primary" })
        </div>
    </div>
}

<div class="row border rounded p-1 m-1 vertical-align">
    <div class="col-lg-3">
        <b>Всего : @Model.Length шт.</b>
    </div>
</div>