Faradise.Design.Admin/Controllers/BannerController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Faradise.Design.Admin.Services;
using Faradise.Design.Admin.Services.Classes;
using Faradise.Design.Controllers.API.Models.Banner;
using Microsoft.AspNetCore.Mvc;

namespace Faradise.Design.Admin.Controllers
{
    public class BannerController : Controller
    {
        private HttpService _http;
        private const string BannerApi = "api/admin/banner";

        public BannerController(HttpService http)
        {
            _http = http;
        }

        [HttpGet("banners-list")]
        public async Task<IActionResult> BannerList()
        {
            var data = (await _http.Get<BannerListModel>($"{BannerApi}/get-banners-list")).Result;
            return await Task.FromResult(View(data));
        }

        [HttpPost("create-banner")]
        public async Task<IActionResult> CreateBannerModel(string name)
        {
            var model = new BannerModel {Name = name};
            ViewData["Categories"] = await _http.FillCategories();
            ViewData["Brands"] = await _http.FillBrands();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateBanner(BannerModel model)
        {
            await _http.Post<int>($"{BannerApi}/create-banner", model);
            return RedirectToAction("BannerList");
        }

        [HttpGet("edit-banner")]
        public async Task<IActionResult> EditBanner(int id)
        {
            var model = (await _http.Get<BannerModel>($"{BannerApi}/get-banner",
                new Dictionary<string, string> {{nameof(id), id.ToString()}})).Result;
            ViewData["Categories"] = await _http.FillCategories();
            ViewData["Brands"] = await _http.FillBrands();
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> UpdateBanner(BannerModel model)
        {
            await _http.Post<bool>($"{BannerApi}/update-banner", model);
            return RedirectToAction("BannerList");
        }

        [HttpPost]
        public async Task<IActionResult> ToggleBannerState(int id)
        {
            await _http.Get<bool>($"{BannerApi}/toggle-banner-state",
                new Dictionary<string, string> {{nameof(id), id.ToString()}});
            return RedirectToAction("BannerList");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBanner(int id)
        {
            await _http.Get<bool>($"{BannerApi}/delete-banner",
                new Dictionary<string, string> {{nameof(id), id.ToString()}});
            return RedirectToAction("BannerList");
        }

        [HttpGet("picture-preview")]
        public ActionResult PicturePreview(string url)
        {
            return PartialView(model:url);
        }

    }
}

Faradise.Design.Admin/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Faradise.Design.Admin.Services;
using Faradise.Design.Controllers.API.Models.Mailing;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Faradise.Design.Admin.Controllers
{
    [ResponseCache(NoStore = true)]
    public class ClientController : Controller
    {
        private HttpService _http = null;

        public ClientController(HttpService http)
        {
            _http = http;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SmsMailing()
        {
            return View();
        }

        [HttpPost("client/send-mails")]
        public async Task<IActionResult> SendMails(string ids, string messageSms)
        {
            if (ids == null)
            {
                return await Task.FromResult(RedirectToAction("SmsMailing"));
            }
            var idsArr = ids.Trim().Split(',');
            var numbersIds = idsArr.Select(x => Convert.ToInt32(x)).ToArray();
            var response = await _http.Post<List<MailingResponseModel>>("/api/mailing/send-sms", new MailingModel { Ids = numbersIds, Message = messageSms });
            return await Task.FromResult(View(response.Result));
        }
    }
}

Faradise.Design.Admin/Views/Shared/BadgeHasChanges.cshtml
@model System.Boolean

@if (Model)
{
    <span class="badge alert-warning">Есть сообщения</span>
}
else
{
    <span class="badge alert-success">Новостей нет</span>
}

Faradise.Design.Admin/Views/Shared/BadgeNeedHelp.cshtml
@model System.Boolean

@if (Model)
{
    <span class="badge badge-danger">Нужна помощь</span>
}
else
{
    <span class="badge badge-success">Жалоб нет</span>
}

Faradise.Design.Admin/Views/Shared/BadgeOrderStatus.cshtml
@using Faradise.Design.Models.Enums
@model OrderStatus

@if (Model == OrderStatus.Created)
{
    <span class="badge badge-warning">Создан</span>
}
else if (Model == OrderStatus.WaitingForPayment)
{
    <span class="badge badge-secondary">Ждет оплаты</span>
}
else if (Model == OrderStatus.WaitingForCreditApprove)
{
    <span class="badge badge-success">Кредит/Ждем одобрения</span>
}
else if (Model == OrderStatus.CreditApprovedWaitingForManager)
{
    <span class="badge badge-success">Кредит/Одобрен/Заказ не отправлен</span>
}
else if (Model == OrderStatus.Paid)
{
    <span class="badge badge-success">Оплачен</span>
}
else if (Model == OrderStatus.InWork)
{
    <span class="badge badge-info">В работе</span>
}
else if (Model == OrderStatus.CreditApprovedInWork)
{
    <span class="badge badge-info">Кредит/Одобрен/В работе</span>
}
else if (Model == OrderStatus.Completed)
{
    <span class="badge badge-dark">Закрыт</span>
}
else if (Model == OrderStatus.Canceled)
{
    <span class="badge badge-danger">Отменен</span>
}
else if (Model == OrderStatus.CreditNotApproved)
{
    <span class="badge badge-danger">Кредит/Не одобрен</span>
}
else if (Model == OrderStatus.CanceledCredit)
{
    <span class="badge badge-danger">Кредит/Отменен</span>
}

Faradise.Design.Admin/Views/Shared/BadgePaymentMethod.cshtml
@using Faradise.Design.Models.Enums
@model PaymentMethod

@if (Model == PaymentMethod.YandexKassa)
{
    <span class="badge badge-warning">Яндекс</span>
}
else if (Model == PaymentMethod.Cash)
{
    <span class="badge badge-secondary">Наличные</span>
}
else if (Model == PaymentMethod.Tinkoff)
{
    <span class="badge badge-info">Tinkoff</span>
}

Faradise.Design.Admin/Views/Shared/BoolBadge.cshtml
@model System.Boolean

@if (Model)
{
    <span class="badge badge-success">Да</span>
}
else
{
    <span class="badge badge-danger">Нет</span>
}

Faradise.Design.Admin/Views/Shared/CompilationSourceBadge.cshtml
@using Faradise.Design.Models.Enums
@model CompilationSource

@if (Model == CompilationSource.Categories)
{
    <span class="badge badge-info">Категории</span>
}
else if (Model == CompilationSource.ProductList)
{
    <span class="badge badge-secondary">Список продуктов</span>
}

Faradise.Design.Admin/Views/Shared/ProjectDescription.cshtml
@model AdminProjectModel

<div class="card m-2">
    <h6 class="card-header">Базовая информация</h6>
    <div class="card-body">

        @if (Model.FillTime != DateTime.MinValue)
        {
            <div class="row">
                <div class="col-lg-2"><b>Дата заполнения: </b></div>
                <div class="col-lg-4">@Model.FillTime</div>
            </div>
        }

        <br />

        <div class="row">
            <div class="col-lg-2"><b>Id клиента: </b></div>
            <div class="col-lg-4">@Model.ClientId</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Имя: </b></div>
            <div class="col-lg-4">@Model.ClientName</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Телефон: </b></div>
            <div class="col-lg-4">@Model.ClientPhone</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Почта: </b></div>
            <div class="col-lg-4">@Model.ClientEmail</div>
        </div>

        <br />

        <div class="row">
            <div class="col-lg-2"><b>Имя проекта: </b></div>
            <div class="col-lg-4">@Model.Name</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Город: </b></div>
            <div class="col-lg-4">@Model.City</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Тип объекта: </b></div>
            <div class="col-lg-4">@Model.ObjectType</div>
        </div>

        <br />

        <div class="row">
            <div class="col-lg-2"><b>Бюджет на мебель: </b></div>
            <div class="col-lg-4">@Model.BudgetFurniture</div>
        </div>

        <div class="row">
            <div class="col-lg-2"><b>Бюджет на ремонт: </b></div>
            <div class="col-lg-4">@Model.BudgetRenovation</div>
        </div>

        <div class="row p-1 m-2">
            <div class="col-lg-auto">
                @using (Html.BeginForm("DeleteProjectDescription", "project", new { projectId = Model.Id }))
                {
                    <input type="button" class="btn btn-outline-success" value="Удалить проект" onclick="return DeleteProject(this.form);" />
                }
            </div>
            <div class="col-lg-auto">
                @using (Html.BeginForm("DeleteUserDescription", "project", new { userId = Model.ClientId }))
                {
                    <input type="button" class="btn btn-outline-success" value="Удалить пользователя" onclick="return DeleteUser(this.form);" />
                }
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    function DeleteProject(form) {
        var isOk = confirm("Вы уверены что хотите удалить проект?");
        if (isOk == true) {
            form.submit();
        }
    }

    function DeleteUser(form) {
        var deleteText = prompt('Вы уверены что хотите удалить пользователя? Если да, то введите слово УДАЛИТЬ', '');
        if (deleteText === 'УДАЛИТЬ') {
            var isOk = confirm("Вы точно уверены?");
            if (isOk == true) {
                form.submit();
            }
        }
        else{
            alert("Не удалено!");
        }
    }
</script>

<div class="card m-2">
    <h6 class="card-header">Причины</h6>
    <div class="card-body">

        @foreach (var r in Model.Reasons)
        {
            <span><b>@r.Name.Localize()</b></span>
            <br />
            <span>@r.Description</span>
            <br />
            <br />
        }
    </div>
</div>

<div class="card m-2">
    <h6 class="card-header">Комнаты</h6>
    <div class="card-body">
        @foreach (var r in Model.Rooms.GroupBy(x => x))
        {
            <div class="row">
                <div class="col-lg-2"><b>@r.Key.Localize()</b></div>
                <div class="col-lg-2">@r.Count()</div>
            </div>
        }
    </div>
</div>

<div class="card m-2">
    <h6 class="card-header">Стили</h6>
    <div class="card-body">
        @foreach (var r in Model.Styles)
        {
            <span><b>@r.Name</b></span>
            <br />
            <span>@r.Description</span>
            <br />
        }
    </div>
</div>

<div class="card m-2">
    <h6 class="card-header">Опросник</h6>
    <div class="card-body">
        @{
            var testing = (TestingViewModel)ViewBag.Testing;
        }
        @foreach (var q in Model.TestAnswers.Questions.Where(x => testing.Questions.ContainsKey(x.Index)))
        {
            <span><b>@testing.Questions[q.Index].Text</b></span>
            <br />
            <span>@testing.Questions[q.Index].Answers[q.Answer]</span>
            <br />
            <br />
        }
    </div>
</div>

<div class="card m-2">
    <h6 class="card-header">Требования к дизайнеру</h6>
    <div class="card-body">
        @if (Model.DesignerRequirements != null)
        {
            <div class="row">
                <div class="col-lg-2"><b>Пол: </b></div>
                <div class="col-lg-4">@Model.DesignerRequirements.Gender</div>
            </div>

            <div class="row">
                <div class="col-lg-2"><b>Возраст: </b></div>
                <div class="col-lg-4">@(Model.DesignerRequirements.AgeFrom + " - " + Model.DesignerRequirements.AgeTo)</div>
            </div>

            <div class="row">
                <div class="col-lg-2"><b>Персональный контроль: </b></div>
                <div class="col-lg-4">@Html.Partial("BoolBadge", Model.DesignerRequirements.NeedPersonalСontrol)</div>
            </div>

            <div class="row">
                <div class="col-lg-2"><b>Личная встреча: </b></div>
                <div class="col-lg-4">@Html.Partial("BoolBadge", Model.DesignerRequirements.NeedPersonalMeeting)</div>
            </div>

            <div class="row">
                <div class="col-lg-2"><b>Место встречи: </b></div>
                <div class="col-lg-4">@Model.DesignerRequirements.MeetingAdress</div>
            </div>
        }
    </div>
</div>

Faradise.Design.Admin/Views/Shared/ProjectPreparation.cshtml
@model AdminProjectModel

<div class="container-fluid m-1">
    <div class="card">
        <h6 class="card-header" data-toggle="collapse" href="#collapse-rooms" role="button" aria-expanded="true" aria-controls="collapse-rooms">
            Комнаты
        </h6>
        <div class="collapse" id="collapse-rooms">
            <div class="card card-body">
                <div class="accordion" id="accordion_p">
                    @foreach (var p in Model.RoomInfosAndProportions)
                    {
                        var id = "car_" + p.RoomId;
                        var c_id = "c_" + p.RoomId;
                        var h_id = "head_" + p.RoomId;

                        <div class="card">

                            <div class="card-header" id="@h_id">
                                <h6 class="mb-0">
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#@c_id" aria-expanded="true" aria-controls="@c_id">
                                        @p.Purpose.Localize()
                                    </button>
                                    @using (Html.BeginForm("DeleteRoom", "project", new { roomId = p.RoomId, projectId=Model.Id }))
                                    {
                                        <input type="submit" class="btn btn-outline-warning" value="Удалить комнату" />
                                    }
                                </h6>
                            </div>

                            <div id="@c_id" class="collapse p-3" aria-labelledby="@h_id" data-parent="#accordion_p">

                                <b><span>План комнаты</span></b>
                                <br />
                                @if (!string.IsNullOrEmpty(p.PlanLink))
                                {
                                    <img class="d-block" src="@p.PlanLink" style="width:600px;">
                                }
                                else
                                {
                                    <span>План комнаты отсутствует</span>
                                }

                                <br />
                                <br />
                                <b><span>Фотографии</span></b>
                                <br />

                                @if (p.Photos != null && p.Photos.Any())
                                {
                                    <div id="@id" class="carousel slide" data-ride="carousel" style="width: 360px;">
                                        <div class="carousel-inner">
                                            @for (var i = 0; i < p.Photos.Count; i++)
                                            {
                                                var cs = "carousel-item";
                                                @if (i == 0)
                                                {
                                                    cs = "carousel-item active";
                                                }

                                                <div class="@cs">
                                                    <img class="d-block" style="height:400px;" src="@p.Photos[i].Link" alt="@p.Photos[i].PhotoId">
                                                </div>
                                            }

                                        </div>
                                        <a class="carousel-control-prev" href="#@id" role="button" data-slide="prev">
                                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                        <a class="carousel-control-next" href="#@id" role="button" data-slide="next">
                                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    </div>
                                }
                                else
                                {
                                    <span>Фотографии не загружены</span>
                                }

                                <br />
                                <br />
                                <b><span>Пропорции</span></b>

                                <div class="row p-1 m-2">
                                    <div class="col-lg-2"><b>Сторона А</b></div>
                                    <div class="col-lg-2">@p.Proportions.SideA</div>
                                </div>
                                <div class="row p-1 m-2">
                                    <div class="col-lg-2"><b>Сторона B</b></div>
                                    <div class="col-lg-2">@p.Proportions.SideB</div>
                                </div>
                                <div class="row p-1 m-2">
                                    <div class="col-lg-2"><b>Высота двери</b></div>
                                    <div class="col-lg-2">@p.Proportions.HeightDoor</div>
                                </div>
                                <div class="row p-1 m-2">
                                    <div class="col-lg-2"><b>Ширина двери</b></div>
                                    <div class="col-lg-2">@p.Proportions.WidthDoor</div>
                                </div>
                                <div class="row p-1 m-2">
                                    <div class="col-lg-2"><b>Высота потолка</b></div>
                                    <div class="col-lg-2">@p.Proportions.HeightCeiling</div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid m-1">
    <div class="card">

        <h6 class="card-header" data-toggle="collapse" href="#collapse-old" role="button" aria-expanded="true" aria-controls="collapse-old">
            Фото того, что останется
        </h6>
        <div class="collapse p-3" id="collapse-old">
            @if (Model.OldStuffPhotos != null && Model.OldStuffPhotos.FurniturePhotos != null && Model.OldStuffPhotos.FurniturePhotos.Any())
            {
                <span>Фотографии старых вещей</span>
                <br/>
                @foreach (var photo in Model.OldStuffPhotos.FurniturePhotos)
                {
                    <img src="@photo.Link" style="height:400px;" />
                    <br />
                }
            }
            else
            {
                <span>Фотографий старых вещей нет</span>
            }

            <br />

            @if (Model.OldStuffPhotos != null && Model.OldStuffPhotos.FurnishPhotos != null && Model.OldStuffPhotos.FurnishPhotos.Any())
            {
                <span>Фотографии старого ремонта</span>
                <br/>
                @foreach (var photo in Model.OldStuffPhotos.FurnishPhotos)
                {
                    <img src="@photo.Link" style="height:400px;" />
                }
            }
            else
            {
                <span>Фотографий старого ремонта нет</span>
            }
        </div>
    </div>
</div>

Faradise.Design.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>_Layout</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body class="p-1 border rounded">
<div class="container-fluid p-3">
    <div class="row border rounded p-4 m-1">
        <h4>Добро пожаловать, Анастасия!</h4>
    </div>
    <div class="row border rounded p-4 m-1">
        <div class="col-lg-2">
            <ul class="nav flex-column border rounded p-3">
                <li class="nav-item"><h5>Маркетплейс</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("companylist", "marketplace", new {showAdditionalInfo = false})">Партнёры</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("BannerList", "Banner")">Баннеры</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("categorylist", "marketplace")">Категории</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ProblemPartnersList", "CorruptedPictures")">Поврежденные картинки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ParametersList", "CategoryParameters")">Параметры категорий</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("roomlist", "marketplace")">Комнаты для категорий</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("colorlist", "marketplace")">Цвета</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ColorMapping", "marketplace")">Соотнесение цветов</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ymlvalidation", "marketplace")">Проверка YML</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("YmlUploadQueue", "marketplace")">Очередь загрузки YML</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("DownloadYml", "product")">Сформировать YML по продуктам</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Moderation", "marketplace")">Нейросеть</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ProductsStats", "marketplace")">Характеристики товаров</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("FindProduct", "marketplace")">Найти товар</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SavedBaskets", "marketplace")">Сохраненные корзины</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CompilationList", "admincompilation")">Акции</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("BadgeList", "adminbadge")">Шилды</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SaleList", "adminsale")">Скидки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("ARProductList", "AdminARProduct")">AR объекты</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("GetPossibleProductsWithDefaultKoef", "DailyProduct")">Товар дня</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Lottery", "marketplace")">Лотерея</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("PromoCodeList", "PromoCode")">Промокоды</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("CollectionBlacklist", "CollectionBlacklist")">Запрщенные коллекции</a>
                </li>
                <li class="nav-divider"><br /></li>

                <li class="nav-item"><h5>Проекты</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SmsMailing", "Client")">Рассылка смс клиентам</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("descriptionlist", "project")">Ждут дизайнера</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("developmentlist", "project")">В работе</a>
                </li>
                <li class="nav-divider"><br /></li>

                <li class="nav-item"><h5>Дизайнеры</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("registeredlist", "designer")">Зарегистрировались</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("applicationlist", "designer")">Заявки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("approvedlist", "designer")">Не заполнили информацию</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("readylist", "designer")">Готовы к работе</a>
                </li>
                <li class="nav-divider"><br /></li>

                <li class="nav-item"><h5>Заказы</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("orderlist", "basket")">Из корзины</a>
                </li>
                <li class="nav-divider"><br /></li>
                <li class="nav-item"><h5>Толока</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("TolokaTasks", "toloka")">Задачи</a>
                </li>
                <li class="nav-divider"><br /></li>
                <li class="nav-item"><h5>Сервисы</h5></li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Status", "BackgroundServices")">Статус</a>
                </li>
                <li class="nav-divider"><br /></li>
            </ul>
        </div>
        <div class="col border rounded">
            <div class="row border rounded m-2 p-3 bg-light">
                <h4>@ViewData["Title"]</h4>
            </div>
            <div class="row border rounded m-2 p-2">
                <div class="container-fluid p-2">
                    @RenderBody()
                    @RenderSection("scripts", required: false)
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="panel-footer">
    <a>faradise, 2018</a>
</footer>
</body>
</html>