Faradise.Design.Admin/Models/Category.cs
namespace Faradise.Design.Admin.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Faradise.Design.Admin/Controllers/MarketplaceController.cs
using Faradise.Design.Admin.Models;
using Faradise.Design.Admin.Services;
using Faradise.Design.Controllers.API.Models.Admin;
using Faradise.Design.Controllers.API.Models.Admin.Marketpace;
using Faradise.Design.Controllers.API.Models.Marketplace;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Mime;
using System.Threading.Tasks;
using Faradise.Design.Admin.Services.Classes;
using Faradise.Design.Controllers.API.Models.Admin.Company;
using Faradise.Design.Controllers.API.Models.Tilda;
using Faradise.Design.Models.Admin.Company;
using Faradise.Design.Models.CategoryParameters;
using Newtonsoft.Json;

namespace Faradise.Design.Admin.Controllers
{
    [Route("marketplace")]
    [ResponseCache(NoStore = true)]
    public class MarketplaceController : Controller
    {
        private HttpService _http = null;

        private static SelectList _categories = null;
        private static RoomNameModel[] _rooms = null;
        private static YmlValidationModel _lastYmlValidation = null;

        public MarketplaceController(HttpService http)
        {
            _http = http;
        }

        [HttpGet("company")]
        public async Task<IActionResult> CompanyList(bool showAdditionalInfo)
        {
            var response = await _http.Get<CompaniesModel>("/api/admin/marketplace/get-companies", new Dictionary<string, string> { { "loadAdditinalInfo", showAdditionalInfo.ToString() } });
            var model = response.Result;

            return await Task.FromResult(View(model));
        }

        [HttpGet("company/{id}")]
        public async Task<IActionResult> Company(int id)
        {
            var response = await _http.Get<CompanyModel>("/api/admin/marketplace/get-company?id=" + id);

            var model = response.Result;
            model.AdditionalNotes = model.AdditionalNotes ?? new List<string>();

            return await Task.FromResult(View(model));
        }

        [HttpGet("enable-company/{id}")]
        public async Task<IActionResult> EnableCompany(int id)
        {
            var resp = await _http.Post<bool>("/api/admin/marketplace/enable-company", new CompanyIdModel() { Id = id });
                        
            return await Task.FromResult(RedirectToAction("Company", new { id }));
        }

        [HttpGet("disable-company/{id}")]
        public async Task<IActionResult> DisableCompany(int id)
        {
            var resp = await _http.Post<bool>("/api/admin/marketplace/disable-company", new CompanyIdModel() { Id = id });

            return await Task.FromResult(RedirectToAction("Company", new { id }));
        }

        [HttpPost("company/create")]
        public async Task<IActionResult> CreateCompany()
        {
            var response = await _http.Post<CreatedCompanyModel>("/api/admin/marketplace/create-company");
            var model = response.Result;

            return await Task.FromResult(RedirectToAction("Company", new { id = model.Id }));
        }

        [HttpPost("company/modify")]
        public async Task<IActionResult> ModifyCompany([FromForm] ModifyCompanyModel model)
        {
            var response = await _http.Post<bool>("/api/admin/marketplace/modify-company", model);
            var success = response.Result;

            return await Task.FromResult(RedirectToAction("Company", new { id = model.Id }));
        }

        [HttpPost("company/addCompanyNote")]
        public async Task<IActionResult> AddCompanyNote([FromForm] int companyId, [FromForm] string newContent)
        {
            var response = await _http.Post<bool>("/api/admin/marketplace/add-company-note", new AddCompanyNoteModel { CompanyId = companyId, Note = newContent });
            return await Task.FromResult(RedirectToAction("Company", new { id = companyId }));
        }

        [HttpPost("company/deleteCompanyNote")]
        public async Task<IActionResult> DeleteCompanyNote([FromForm] int companyId, [FromForm] int noteId)
        {
            var response = await _http.Post<bool>("/api/admin/marketplace/delte-company-note", new DeleteCompanyNoteModel { CompanyId = companyId, NoteId = noteId });
            return await Task.FromResult(RedirectToAction("Company", new { id = companyId }));
        }

        [HttpPost("company/saveCompanyNotes")]
        public async Task<IActionResult> SaveCompanyNotes([FromForm] int companyId, [FromForm] int noteId, [FromForm] string newContent)
        {
            var response = await _http.Post<bool>("/api/admin/marketplace/change-company-note", new ChangeCompanyNoteModel { CompanyId = companyId, NoteId = noteId, NewNote = newContent });
            return await Task.FromResult(RedirectToAction("Company", new { id = companyId }));
        }

        [DisableRequestSizeLimit]
        [HttpPost("company/{id}/upload")]
        public async Task<IActionResult> Upload(IFormFile file, int id)
        {
            byte[] bytes;
            using (var r = new BinaryReader(file.OpenReadStream()))
                bytes = r.ReadBytes((int)r.BaseStream.Length);

            var content = new ByteArrayContent(bytes);
            var multipart = new MultipartFormDataContent();
            multipart.Add(content, "file", file.FileName);
            multipart.Add(new StringContent(id.ToString()), "id");

            var response = await _http.PostContent<UploadResultModel>("/api/admin/marketplace/upload-yml", multipart);
            var model = response.Result;

            return await Task.FromResult(View(model));
        }

        [HttpPost("company/{id}/reject-upload/{upload}")]
        public async Task<IActionResult> RejectUpload(int id, string upload)
        {
            var content = new PostProcessUploadModel { Id = id, Upload = upload };
            var response = _http.Post<bool>("/api/admin/marketplace/reject-upload", content);
            var success = response.Result;

            return await Task.FromResult(RedirectToAction("Company", new { id }));
        }

        [HttpPost("company/{id}/accept-upload/{upload}")]
        public async Task<IActionResult> AcceptUpload(int id, string upload)
        {
            var content = new PostProcessUploadModel { Id = id, Upload = upload };
            var response = _http.Post<bool>("/api/admin/marketplace/accept-upload", content);
            var success = response.Result;

            return await Task.FromResult(RedirectToAction("Company", new { id }));
        }

        [HttpGet("company/{id}/categories")]
        public async Task<IActionResult> CompanyCategories(int id)
        {
            var response = await _http.Get<AdminCompanyCategoriesModel>("/api/admin/company/company-categories", new Dictionary<string, string> { { "companyId", id.ToString() }, { "filtration", CompanyCategoryFiltration.Unavailable.ToString() } });
            var companyCategories = response.Result;

            // с бека возвращать только количество валидных товаров
            // убирать категории, в которых 0 валидных товаров и нет детей
            // заполнить количество товаров родительских категорий суммой детей + товаров
            // отсортировать по:
            //  есть товары и не назначена категория
            //  есть товары и назначена не листовая категория

            var flat = new List<AdminCompanyCategoryModel>();
            foreach (var c in companyCategories.Categories)
                FlatternCategories(c, flat);
            companyCategories.Categories = flat;

            var categoriesResponse = await _http.Get<CategoriesModel>("/api/admin/marketplace/get-categories");
            var categoriesModel = categoriesResponse.Result;

            var adminCategories = categoriesModel.Categories
                .Select(x => new AdminCategoryModel
                {
                    Id = x.Id,
                    ParentId = x.ParentId,
                    Name = x.Name,
                    DeliveryCost = x.DeliveryCost,
                    DeliveryDays = x.DeliveryDays,
                    Depth = 0
                })
                .ToList();

            var categoriesList = new List<AdminCategoryModel>();

            var root = adminCategories.Where(x => x.ParentId == 0);
            foreach (var cat in root)
                ProcessCategoryHierarchy(cat, adminCategories, categoriesList, 0);

            var categories = categoriesList
                .Select(x => new Category
                {
                    Id = x.Id,
                    Name = FormCategorySelectListName(x.Name, x.Depth)
                })
                .ToList();

            categories.Insert(0, new Category { Id = 0, Name = string.Empty });

            _categories = new SelectList(categories, "Id", "Name");

            var responseRooms= await _http.Get<RoomNameModel[]>("/api/admin/marketplace/get-category-rooms");
            _rooms = responseRooms.Result;

            ViewData["Categories"] = _categories;
            ViewData["Rooms"] = new SelectList(_rooms, "RoomNameId", "Name");

            return await Task.FromResult(View(companyCategories));
        }

        private void FlatternCategories(AdminCompanyCategoryModel cat, List<AdminCompanyCategoryModel> flat)
        {
            flat.Add(cat);

            if (cat.Childs == null || !cat.Childs.Any())
                return;

            foreach (var c in cat.Childs)
                FlatternCategories(c, flat);
        }

        // ЭТО
        [HttpGet("company/{companyId}/categories/{categoryId}")]
        public async Task<IActionResult> CompanyCategory(int companyId, int categoryId)
        {
            var response = await _http.Get<AdminCompanyCategoryItem>("/api/admin/company/company-category", new Dictionary<string, string> { { "companyId", companyId.ToString() }, { "categoryId", categoryId.ToString() } });

Faradise.Design.Admin/Views/Marketplace/CategoryList.cshtml
@model AdminCategoryModel[]

@{
    ViewData["Title"] = "Список цветов для продуктов компаний";
}


@using (Html.BeginForm("CreateCategory", "marketplace"))
{
    <div class="row border rounded p-2 m-2 vertical-align">
        <div class="col-lg-2 text-center">
            @Html.TextBox("name", string.Empty)
        </div>
        <div class="col-lg-1 text-center">
            <input type="submit" class="btn btn-outline-primary" value="Создать новую" />
        </div>
    </div>
}

<br />

@using (Html.BeginForm("ModifyCategoryList", "marketplace"))
{
<div class="row border rounded p-2 m-2 vertical-align">
    <div class="col-lg-3 text-left">
        <b><span>Имя</span></b>
    </div>

    <div class="col-lg-1 text-left">
        <b><span>Пр-т дня</span></b>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>Приоритет</span></b>
    </div>

    <div class="col-lg-2 text-center">
        <b><span>В заголовке</span></b>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>Популярное</span></b>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>Иконка</span></b>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>Статус</span></b>
    </div>
</div>

    @for (var i = 0; i < Model.Length; i++)
    {

        @Html.HiddenFor(x => x[i].Id)
        @Html.HiddenFor(x => x[i].Name)
        @Html.HiddenFor(x => x[i].WasInHeader)
        @Html.HiddenFor(x => x[i].WasPopular)
        @Html.HiddenFor(x => x[i].ImageUrl)
        @Html.HiddenFor(x => x[i].ParentId)

<div class="row border rounded p-2 m-2 vertical-align">
    <div class="col-lg-3 text-left">


        @for (var j = 0; j < Model[i].Depth; j++)
        {
            <span>--</span>
        }

        @if (Model[i].Depth > 0)
        {
            <span>&nbsp;</span>
        }

        <span>@Model[i].Name</span>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>@Model[i].DailyProductPriority</span></b>
    </div>

    <div class="col-lg-1 text-center">
        <b><span>@Model[i].Priority</span></b>
    </div>

    <div class="col-lg-2 text-center">
        @if (Model[i].Depth == 0)
        {
            @Html.CheckBoxFor(x => x[i].InHeader)
        }
    </div>

    <div class="col-lg-1 text-center">
        @if (Model[i].Depth == 0)
        {
            @Html.CheckBoxFor(x => x[i].IsPopular)
        }
    </div>

    <div class="col-lg-1 text-center">
        <img src="@Model[i].ImageUrl" style="height: 24px" />
    </div>

    <div class="col-lg-1 text-center">
        @if (@Model[i].IsEnabled == true)
        {
            <span>Включен</span>
        }
        else
        {
            <span>Отключен</span>
        }
    </div>

    <div class="col-lg-2 text-center">
        @Html.ActionLink("Подробнее", "Category", "marketplace", new { id = Model[i].Id }, new { @class = "btn btn-outline-primary" })
    </div>
</div>
    }

    <div class="row p-2 m-2">
        <input type="submit" class="btn btn-outline-primary" value="Сохранить изменения" />
    </div>
}

Faradise.Design.Admin/Views/Marketplace/CategoryProductsList.cshtml
@model CategoryProductsListModel

@{
    ViewData["Title"] = Model.CompanyCategoryName; //.Category.CompanyCategory;// "Список продуктов";
}

@foreach (var m in Model.Products)
{
<div id="@m.ProductId" class="row border rounded vertical-align m-2 p-2 category">

    <div class="col-lg-3">
        <img src="@m.PhotoUrl" width="200px" />
    </div>

    <div class="col-lg-1">
        ID: @m.ProductId
    </div>

    <div class="col-lg-1">
        @m.ProductName
    </div>

    <div class="col-lg-1">
        <a href="@m.VendorLink">Ссылка на партнера</a>
    </div>

    <div class="col-lg-1">
        <a href="https://faradise.ru/product/@m.ProductId">Ссылка на товар</a>
    </div>

    <div class="col-lg-1">
       В: @m.Height <br>
       Ш: @m.Width <br>
       Д: @m.Length <br>
    </div>

    <div class="col-lg-1">
        @m.CategoryName
    </div>

    <div class="col-lg-2">
        <div class="col-lg-3">
            @Html.DropDownList("Categories", Model.Selector, new { @onchange = $"changeCategory({m.ProductId}, this.value)" })
        </div>
    </div>
</div>
}

@section scripts {
    <script type="text/javascript">

        function getXmlHttp() {
            var xmlhttp;
            try {
                xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
            } catch (e) {
                try {
                    xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                } catch (E) {
                    xmlhttp = false;
                }
            }
            if (!xmlhttp && typeof XMLHttpRequest != 'undefined') {
                xmlhttp = new XMLHttpRequest();
            }
            return xmlhttp;
        }

        function changeCategory(id, val) {
            //console.log(id)
            //console.log(val)

            var xmlhttp = getXmlHttp(); // Создаём объект XMLHTTP
            xmlhttp.open('POST', '/marketplace/category/change-product-category', true); // Открываем асинхронное соединение
            xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded'); // Отправляем кодировку
            xmlhttp.send("id=" + id
                + "&val=" + val); // Отправляем POST-запрос
            xmlhttp.onreadystatechange = function () { // Ждём ответа от сервера
            if (xmlhttp.readyState == 4) { // Ответ пришёл
                if (xmlhttp.status == 200) { // Сервер вернул код 200 (что хорошо)
                    //document.getElementById(id).remove();
                }
            }
        };
        };
    </script>
}

Faradise.Design.Admin/Views/Marketplace/ColorList.cshtml
@model MarketplaceColorModel[]

@{
    ViewData["Title"] = "Наименования цветов";
}

<div class="row border rounded p-1 m-1">
    <div class="col-md-1 text-center">
        <b>ColorId</b>
    </div>
    <div class="col-md-2 text-center">
        <b>Название цвета</b>
    </div>

</div>
@foreach (var color in Model)
{
<div class="row border rounded p-1 m-1">
    <div class="col-md-1 text-center">
        <b>@color.ColorId</b>
    </div>
    <div class="col-md-2 text-center">
        <b>@color.Name</b>
    </div>
    @using (Html.BeginForm("EditColor", "marketplace"))
    {
        @Html.HiddenFor(x => color.ColorId)
        <div class="col-lg-2">
            @Html.TextBoxFor(x => color.Name)
        </div>
        <div class="form-group">
            <label for="color.Hex" class="col-md-4 control-lbl">Цвет:</label>
            <div class="col-md-8">
                <input type="color" name="color.Hex" id="color" class="form-control" value="@color.Hex" />
            </div>
        </div>
        <div class="col-lg-1 text-center">
            <input type="submit" class="btn btn-outline-primary" value="Изменить" />
        </div>
    }
</div>
}

<div class="card m-2">
    @using (Html.BeginForm("AddColor", "Marketplace", FormMethod.Post))
    {
        <input type="text" name="color" />
        <input type="color" name="hex" id="color"/>
        <input type="submit" value="Добавить" />
    }
</div>

Faradise.Design.Admin/Views/Marketplace/ColorMapping.cshtml
@model CompanyColorModel[]

@{
    ViewData["Title"] = "Соответствия цветов";
}

<div class="row border rounded p-1 m-1">
    <div class="col-md-2 text-center">
        <b>Название цвета компании</b>
    </div>
    <div class="col-md-2 text-center">
        <b>Название цвета маркетплейса</b>
    </div>

</div>

@for (var i = 0; i < Model.Length; i++)
{
<div class="row border rounded p-1 m-1">
    <div class="col-md-2 text-center">
        <b>@Model[i].Name</b>
    </div>
    <div class="col-md-2 text-center">
        @if (Model[i].MarketplaceColorId != null)
    {
        <b>@Model[i].MarketplaceColorName</b>

}
else
{

    <b>Не присвоено</b>
}

    </div>
    @using (Html.BeginForm("MapColor", "marketplace"))
    {
        @Html.Hidden("companyColorId",Model[i].Id)
        <div class="col-lg-3">
            @Html.DropDownList("marketplaceColorId", (SelectList)ViewData["MarketplaceColors"])
        </div>
        <div class="col-lg-1 text-center">
            <input type="submit" class="btn btn-outline-primary" value="Привязать" />
        </div>
    }
</div>
}

Faradise.Design.Admin/Views/Marketplace/CompanyCategories.cshtml
@model Faradise.Design.Controllers.API.Models.Admin.Company.AdminCompanyCategoriesModel

@{
    ViewData["Title"] = "Переназначение категорий";
}

@foreach (var m in Model.Categories)
{
    <div id="@m.CompanyCategoryId" class="row border rounded vertical-align m-2 p-2 category">
        
    </div>
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $(".category").each(function(index) {
                var id = $(this).attr("id");
                load(id);
            });
        });

        function load(id) {
            var url = 'categories/' + id;
            $.get(url, function (data) {
                var container = $('#' + id);
                container.html(data);

                $(container).find(".category-selector").change(function () {
                    mapCategory(id, this.value);
                });

                $(container).find("#rooms-all").on('click', function () {
                    checkRooms(id);
                });

                $(container).find("#rooms-none").on('click', function () {
                    uncheckRooms(id);
                });

                $(container).find('.room-toggle').each(function (entry) {
                    $(this).change(function (val) {
                        updateRoom(id, this.value, this.checked);
                    });
                });
            });
        };

        function mapCategory(companyCategoryId, categoryId) {
            var url = 'categories/map/' + companyCategoryId + '/' + categoryId;
            $.get(url, function (data) {
                var array = $.parseJSON(data);
                if (Array.isArray(array)) {
                    array.forEach(function (entry) {
                        load(entry);
                    });
                }
            });
        };

        function uncheckRooms(id) {
            var url = 'categories/' + id + '/remove-rooms';
            $.get(url, function (data) {
                load(id);
            });
        }

        function checkRooms(id) {
            var url = 'categories/' + id + '/add-rooms';
            $.get(url, function (data) {
                load(id);
            });
        }

        function updateRoom(id, roomId, checked) {
            var url = 'categories/' + id + '/update-room/' + roomId + '/' + checked;
            $.get(url, function (data) {
                load(id);
            });
        }
    </script>
}

Faradise.Design.Admin/Views/Marketplace/CompanyCategoryItem.cshtml
@model CompanyCategoryHierarchyModel


<div class="col-lg-4">
    @for (var j = 0; j < Model.Depth; j++)
    {
        <span>---</span>
    }

    @Html.DisplayTextFor(x => x.Category.CompanyCategory)
</div>
<div class="col-lg-1">
    @if (Model.Category.BadCategoryBinding)
    {
        <span class="badge badge-warning">Плохо</span>
    }
    else if (Model.Category.Category == 0 && Model.Category.Products > 0)
    {
        <span class="badge badge-danger">Пропущено</span>
    }
</div>
<div class="col-lg-3">
    @Html.DropDownListFor(x => x.Category.Category, Model.Selector, new { @class = "category-selector" })
</div>
<div class="col-lg-2" style="width:250px;">
    @if (Model.Category.Products > 0)
    {
        <span><b>Товаров: </b></span>
        <span><b>@Model.Category.Products</b></span>
    }
</div>

<div class="col-lg-2">
    @Html.ActionLink("Все товары", "CategoryProductsList", "marketplace", new { companyId = Model.CompanyId, companyCategoryId = Model.Category.CompanyCategoryId }, new { @class = "btn btn-outline-primary" })
</div>

<!--
<br />
<br />

<div class="container-fluid" id="@("collapse" + Model.Category.CompanyCategoryId)">
    <div class="float-sm-right">
        <button type="button" class="btn btn-primary btn-sm" id="rooms-all">все</button>
        <button type="button" class="btn btn-primary btn-sm" id="rooms-none">ни одна</button>
        @foreach (var room in Model.Rooms)
        {
            <label><input type="checkbox" @(Model.Category.Rooms.Any(x => x.RoomNameId == room.RoomNameId) ? "checked=\"\"checked\"" : "") class="room-toggle" value="@room.RoomNameId" />@room.Name</label>
            <span>&nbsp;</span>

        }
    </div>
</div>
-->

Faradise.Design.Admin/Views/Marketplace/CompanyCollections.cshtml
@model AdminCompanyProductCollectionsModel

@{
    ViewData["Title"] = "Коллекции";
}

<div class="container-fluid">

    @using (Html.BeginForm("ManuallyUpdateCompanyCollections", "marketplace"))
    {
        @Html.Hidden("companyId", Model.CompanyId)
        <input type="submit" value="!Обновить коллекции вручную!" class="btn btn-danger m-2" />
    }

    <div class="border rounded p-2 m-1">

        <table class="table table-light text-center align-middle table-sm table-borderless">
            <thead class="thead-dark">
                <tr>

                    <th scope="col">
                        <b><span>Имя</span></b>
                    </th>

                    <th scope="col">
                        <b><span>Keyword</span></b>
                    </th>

                    <th scope="col">
                        <b><span>Доступна</span></b>
                    </th>

                    <th scope="col">
                        <b><span>Продукты</span></b>
                    </th>

                    <th scope="col">
                        <b><span>Подробнее</span></b>
                    </th>

                </tr>
            </thead>

            <tbody>
                @foreach (var collection in Model.Collections)
                {
                    <tr class="border-top">

                        <td scope="row" class="align-middle">
                            <b>@collection.Name</b>
                        </td>

                        <td class="align-middle">
                            <span>@collection.KeyWord</span>
                        </td>

                        <td class="align-middle">
                            @if (@collection.Available)
                            {
                                <span class="text-success"> Вкл. </span>
                            }
                            else
                            {
                                <span class="text-danger"> Выкл. </span>
                            }
                        </td>

                        <td class="align-middle">
                            <span>@collection.ProductCount</span>
                        </td>

                        <td class="font-weight-normal align-right text-right">
                            @Html.ActionLink("Подробнее", "CompanyCollection", new { collectionId = collection.Id }, new { @class = "btn btn-outline-primary" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

Faradise.Design.Admin/Views/Marketplace/RoomList.cshtml
@model RoomNameModel[]

@{
    ViewData["Title"] = "Наименование комнат для фильтра";
}

<div class="row border rounded p-1 m-1">
    <div class="col-md-1 text-center">
        <b>RoomNameId</b>
    </div>
    <div class="col-md-2 text-center">
        <b>Название комнаты</b>
    </div>

</div>
@foreach (var room in Model)
{
    <div class="row border rounded p-1 m-1">
        <div class="col-md-1 text-center">
            <b>@room.RoomNameId</b>
        </div>
        <div class="col-md-2 text-center">
            <b>@room.Name</b>
        </div>
        @using (Html.BeginForm("EditRoomName", "marketplace"))
        {
            @Html.HiddenFor(x => room.RoomNameId)
            <div class="col-lg-2">
                @Html.TextBoxFor(x => room.Name)
            </div>
            <div class="col-lg-1 text-center">
                <input type="submit" class="btn btn-outline-primary" value="Изменить название" />
            </div>
        }
    </div>
}

    <div class="card m-2">
        @using (Html.BeginForm("AddRoomName", "Marketplace", FormMethod.Post))
        {
            <input type="text" name="room" />
            <input type="submit" value="Добавить" />
        }
    </div>

Faradise.Design.Admin/Views/Marketplace/SavedBaskets.cshtml
@using Faradise.Design.Controllers.API.Models.Marketplace;
@model UserSavedBasketsModel

@{
    ViewData["Title"] = "Поиск товаров";
}


<div class="border rounded p-2 m-2">

    @using (Html.BeginForm("SaveBaskets", "Marketplace", FormMethod.Post))
    {
        int userId = 0;
        <input type="number" value="@userId" name="userId" />
        <input hidden="hidden" type="text" value="" name="vendorCode">
        <input type="submit" value="Найти по UserId" />
    }

    <br />


    @if (@Model != null && @Model.UserId != 0)
    {
        @foreach (var p in Model.Baskets)
        {

            <div class="row m-2">
                <div class="col-lg-6"><b>ID: </b> @p.Id </div>
            </div>
            <div class="row m-2">
                <div class="col-lg-6"><b>Ссылка: </b> @p.Link</div>
            </div>
            <div class="row m-2">
                <div class="col-lg-6"><b>Просмотры: </b></div>
            </div>
            @foreach (var view in p.Views)
            {
            <div class="row m-2">
                <div class="col-lg-6"><b>UserId: </b> @view.UserId</div>
                <div class="col-lg-6"><b>Количество просмотров: </b> @view.ViewsCount</div>
            </div>

            }
            
            <br />

        }
    }
</div>

@section scripts {
    <script type="text/javascript">

        
    </script>
}