Faradise.Design.Admin/Models/DailyProducts/SelectDailyProductModel.cs
using Faradise.Design.Controllers.API.Models.Admin.Marketpace;
using Faradise.Design.Controllers.API.Models.Marketplace;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faradise.Design.Admin.Models
{
    public class SelectDailyProductModel
    {
        public DailyProductModel DailyProduct { get; set; }
        public PossibleDailyProductModel[] PossibleProducts { get; set; }
        public float CompanyKoef { get; set; }
        public float CategoryKoef { get; set; }
        public float SaleKoef { get; set; }
        public int Page { get; set; }
        public int SelectedId { get; set; }
    }
}

Faradise.Design.Admin/Controllers/DailyProductController.cs
using Faradise.Design.Admin.Models;
using Faradise.Design.Admin.Services;
using Faradise.Design.Controllers.API.Models.Admin.Marketpace;
using Faradise.Design.Controllers.API.Models.Marketplace;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Faradise.Design.Admin.Controllers
{
    [Route("daily-product")]
    [ResponseCache(NoStore = true)]
    public class DailyProductController : Controller
    {
        public int PRODUCTS_PER_PAGE = 10; 
        private HttpService _http = null;

        public DailyProductController(HttpService http)
        {
            _http = http;
        }

        [HttpGet("get-possible-products-with-default-koef")]
        public async Task<IActionResult> GetPossibleProductsWithDefaultKoef(int page)
        {
            var companyKoef = 1.0f;
            var categoryKoef = 1.0f;
            var saleKoef = 1.0f;
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = page, companyKoef = companyKoef, categoryKoef = categoryKoef, saleKoef = saleKoef }));
        }

        [HttpGet("get-possible-products")]
        public async Task<IActionResult> GetPossibleProducts(int page, float companyKoef, float categoryKoef, float saleKoef)
        {
            //([FromQuery] int offset, [FromQuery] int count, [FromQuery] float companyKoef, [FromQuery] float categoryKoef, [FromQuery] float saleKoef)
            var current = await _http.Get<DailyProductModel>("api/admin/marketplace/daily-products/current");
            var products = await _http.Get<PossibleDailyProductModel[]>("api/admin/marketplace/daily-products/possible", new Dictionary<string, string>
            {
                { "offset" , (PRODUCTS_PER_PAGE * page).ToString() },
                { "count", PRODUCTS_PER_PAGE.ToString() },
                { "companyKoef",  companyKoef.ToString() },
                { "categoryKoef", categoryKoef.ToString() },
                { "saleKoef", saleKoef.ToString() }
            });
            var model = new SelectDailyProductModel
            {
                CategoryKoef = categoryKoef,
                CompanyKoef = companyKoef,
                SaleKoef = saleKoef,
                DailyProduct = current.Result,
                PossibleProducts = products.Result,
                Page = page,
                SelectedId = 0
            };
            return await Task.FromResult(View(model));
        }

        [HttpPost("refresh-page")]
        public async Task<IActionResult> RefreshPage(SelectDailyProductModel model)
        {
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = model.Page, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
        }

        [HttpPost("next-page")]
        public async Task<IActionResult> NextPage(SelectDailyProductModel model)
        {
            var nextPage = model.Page + 1;
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = nextPage, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
        }

        [HttpPost("prev-page")]
        public async Task<IActionResult> PrevPage(SelectDailyProductModel model)
        {
            int nextPage = Math.Max(0, model.Page - 1);
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = nextPage, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
        }

        [HttpPost("set-page")]
        public async Task<IActionResult> SetPage(SelectDailyProductModel model)
        {
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = model.Page, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
        }

        [HttpPost("select-product")]
        public async Task<IActionResult> SelectProduct(SelectDailyProductModel model)
        {
            if (model.SelectedId < 1)
                return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = model.Page, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
            await _http.Post<bool>("api/admin/marketplace/daily-products/set-daily-product", new SetDailyProductModel { ProductId = model.SelectedId });
            return await Task.FromResult(RedirectToAction("GetPossibleProducts", new { page = model.Page, companyKoef = model.CompanyKoef, categoryKoef = model.CategoryKoef, saleKoef = model.SaleKoef }));
        }

        [HttpGet("previous-list")]
        public async Task<IActionResult> PreviousList()
        {
            var response = await _http.Get<DailyProductModel[]>("api/admin/marketplace/daily-products/previous-list");
            var result = response.Result ?? new DailyProductModel[0];
            return await Task.FromResult(View(result));
        }
    }
}

Faradise.Design.Admin/Controllers/ProductController.cs
using System.Collections.Generic;
using Faradise.Design.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Faradise.Design.Admin.Services;
using Faradise.Design.Models.Admin.Product;
using System;
using System.IO;

namespace Faradise.Design.Admin.Controllers
{
    [Route("product")]
    public class ProductController : Controller
    {
        private HttpService _http = null;

        public ProductController(HttpService http)
        {
            _http = http;
        }

        [HttpGet("images-priority/{id}")]
        public async Task<IActionResult> ImagesPriority(int id)
        {
            var response = await _http.Get<ProductImages>("api/admin/product/images-priority", new Dictionary<string, string> {{"productId", id.ToString()}});
            var model = response.Result;

            return View(model);
        }

        [HttpPost("set-images-priority")]
        public async Task<IActionResult> SetImagesPriority([FromForm] ProductImages model)
        {
            var response = await _http.Post<bool>("api/admin/product/set-images-priority", model);
            return RedirectToAction("ImagesPriority", new {id = model.ProductId});
        }

        [HttpGet]
        public async Task<IActionResult> SetImagesPriorityy([FromForm] ProductImages model)
        {
            var response = await _http.Post<bool>("api/admin/product/set-images-priority", model);
            return RedirectToAction("ImagesPriority", new { id = model.ProductId });
        }

        [HttpGet("download-yml")]
        public async Task<IActionResult> DownloadYml()
        {
            return View(new ModifyProductCompilationModel());
        }

        [HttpPost("download-feed-by-ids")]
        public async Task<IActionResult> ModifyProductCompilation(ModifyProductCompilationModel modifymodel)
        {
            var products = ParseProducts(modifymodel.ProductString);
            var response = await _http.Post<byte[]>("api/admin/feed/get-feed-by-ids", products);
            var bytes = response.Result;
            var file = File(bytes, "application/xml", modifymodel.Name+".xml");
            return file;
        }



        private int[] ParseProducts(string productString)
        {
            if (string.IsNullOrEmpty(productString))
                return new int[0];
            var split = productString.Split(new char[] { '\n', '\r', '\t', ';', ',', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (split.Length < 1)
                return new int[0];
            var productList = new List<int>();
            foreach (var s in split)
            {
                int productId = 0;
                if (int.TryParse(s, out productId))
                {
                    productList.Add(productId);
                }
            }
            return productList.ToArray();
        }
    }
}

Faradise.Design.Admin/Views/DailyProduct/GetPossibleProducts.cshtml
@model SelectDailyProductModel

@{
    ViewData["Title"] = "Товар дня";
}

<div class="container-fluid">

    <div class="row border rounded vertical-align m-2 p-2">

        <div class="col-lg-12">
            Приоритет товара  =  приоритет_компании * вес_компании + приоритет_категории * вес_категории + скидка * вес_скидки
        </div>
        <br />

    </div>
    <div class="row">
        @using (Html.BeginForm("RefreshPage", "DailyProduct"))
        {
            <div class="form-group-lg">
                <div class="col-lg-1">
                    вес_компании
                </div>
                <div class="col-lg-1">
                    @Html.TextBox("CompanyKoef", Model.CompanyKoef)
                </div>
            </div>
            <div class="form-group-lg">
                <div class="col-lg-1">
                    вес_категории
                </div>
                <div class="col-lg-1">
                    @Html.TextBox("CategoryKoef", Model.CategoryKoef)
                </div>
            </div>
            <div class="form-group-lg">
                <div class="col-lg-1">
                    вес_скидки
                </div>
                <div class="col-lg-1">
                    @Html.TextBox("SaleKoef", Model.SaleKoef)
                </div>
            </div>
            <br />
            @Html.Hidden("Page", Model.Page)
            <input type="submit" class="btn btn-success" value="Применить" />
        }
    </div>

    <br />
    <br />

    <div class="row border rounded vertical-align m-2 p-2">
        Продукт дня:
    </div>

    <div class="row border rounded vertical-align m-2 p-2">

        @if (Model.DailyProduct != null)
    {

        <div class="col-lg-2">
            Установлен : @Model.DailyProduct.OfferTime.AddHours(3).ToString("dd.MM.yy HH:mm")
        </div>

        <div class="col-lg-3">
            <img src="@Model.DailyProduct.Product.PhotoUrl" width="200px" />
        </div>

        <div class="col-lg-1">
            ID: @Html.ActionLink(Model.DailyProduct.Product.Id.ToString(), "ImagesPriority", "Product", new { id = Model.DailyProduct.Product.Id })
        </div>

        <div class="col-lg-1">
            @Model.DailyProduct.Product.Name
        </div>

        <div class="col-lg-1">
            @Model.DailyProduct.Product.Price
        </div>
        <div class="col-lg-1">
            @if (Model.DailyProduct.Product.PreviousPrice.HasValue)
            {
                <span>@((int)(100 - @Model.DailyProduct.Product.Price * 100.0f / @Model.DailyProduct.Product.PreviousPrice))%</span>
            } else { <span>0%</span> }
        </div>
        <div class="col-lg-1">
            @Model.DailyProduct.Product.PreviousPrice
        </div>

        <div class="col-lg-1">
            @Model.DailyProduct.Product.CompanyName
        </div>

        <div class="col-lg-1">
            <a href="https://faradise.ru/product/@Model.DailyProduct.Product.Id">Ссылка на товар</a>
        </div>
}
else
{
    <div class="col-lg-3">
        Не установлен
    </div>
}
    </div>

    <div class="row vertical-align m-2 p-2">
        @Html.ActionLink("Прошлые товары дня", "PreviousList", "DailyProduct", null, new { @class = "btn btn-outline-primary" })
    </div>

    <br />
    <br />

    <div class="row border rounded vertical-align m-2 p-2">
        <div class="col-lg-2">
            @using (Html.BeginForm("SetPage", "DailyProduct"))
            {
                <div class="form-group">
                    <label>Страница: </label>
                    <div class="col-lg-2">
                        @Html.TextBox("page", Model.Page)
                        @Html.Hidden("categorykoef", Model.CategoryKoef)
                        @Html.Hidden("companykoef", Model.CompanyKoef)
                        @Html.Hidden("salekoef", Model.SaleKoef)
                        <input type="submit" class="btn btn-info" value="Перейти" />
                    </div>
                </div>
            }
        </div>
        <div class="col-lg-1">
            @using (Html.BeginForm("PrevPage", "DailyProduct"))
            {
                @Html.Hidden("CategoryKoef", Model.CategoryKoef)
                @Html.Hidden("CompanyKoef", Model.CompanyKoef)
                @Html.Hidden("SaleKoef", Model.SaleKoef)
                @Html.Hidden("Page", Model.Page)
                <input type="submit" class="btn btn-info" value="<" />
            }
        </div>
        <div class="col-lg-1">
            @using (Html.BeginForm("NextPage", "DailyProduct"))
            {
                @Html.Hidden("CategoryKoef", Model.CategoryKoef)
                @Html.Hidden("CompanyKoef", Model.CompanyKoef)
                @Html.Hidden("SaleKoef", Model.SaleKoef)
                @Html.Hidden("Page", Model.Page)
                <input type="submit" class="btn btn-info" value=">" />
            }
        </div>
    </div>

    <br/>

    <div class="row border rounded vertical-align m-2 p-2">
        <div class="col-lg-2">
            Фото
        </div>

        <div class="col-lg-1">
            ID
        </div>

        <div class="col-lg-2">
            Имя
        </div>

        <div class="col-lg-1">
            Цена
        </div>
        <div class="col-lg-1">
            Скидки
        </div>
        <div class="col-lg-1">
            Старая
        </div>

        <div class="col-lg-1">
            Партнёр
        </div>

        <div class="col-lg-1">
            Ссылка
        </div>
    </div>

    @foreach (var m in Model.PossibleProducts)
    {
        <div class="row border rounded vertical-align m-1 p-2">

            <div class="col-lg-2 text-center">
                <img src="@m.PhotoUrl" width="180px" />
            </div>

            <div class="col-lg-1">
                ID: @Html.ActionLink(m.Id.ToString(),"ImagesPriority", "Product", new { id = m.Id }) (@m.TotalPriority)
            </div>

            <div class="col-lg-2">
                @m.Name
            </div>

            <div class="col-lg-1">
                @m.Price
            </div>
            <div class="col-lg-1">
                @if (m.PreviousPrice.HasValue)
                {
                    <span>@((int)(100 - @m.Price * 100.0f / @m.PreviousPrice))%</span>
                } else { <span> 0% </span> }
            </div>
            <div class="col-lg-1">
                @m.PreviousPrice
            </div>

            <div class="col-lg-1">
                @m.CompanyName
            </div>

            <div class="col-lg-1">
                <a href="https://faradise.ru/product/@m.Id">Ссылка на товар</a>
            </div>

            @using (Html.BeginForm("SelectProduct", "DailyProduct"))
            {
                @Html.Hidden("CategoryKoef", Model.CategoryKoef)
                @Html.Hidden("CompanyKoef", Model.CompanyKoef)
                @Html.Hidden("SaleKoef", Model.SaleKoef)
                @Html.Hidden("Page", Model.Page)
                @Html.Hidden("SelectedId", m.Id)

                <div class="col-lg-1">
                    <input type="submit" class="btn btn-success" value="Выбрать" />
                </div>
            }
        </div>
    }
    <div class="row border rounded vertical-align m-2 p-2">
        <div class="col-lg-2">
            @using (Html.BeginForm("SetPage", "DailyProduct"))
            {
                <div class="form-group">
                    <label>Страница: </label>
                    <div class="col-lg-2">
                        @Html.TextBox("page", Model.Page, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.Hidden("categorykoef", Model.CategoryKoef)
                        @Html.Hidden("companykoef", Model.CompanyKoef)
                        @Html.Hidden("salekoef", Model.SaleKoef)
                        <input type="submit" class="btn btn-info" value="Перейти" />
                    </div>
                </div>
            }
        </div>
        <div class="col-lg-1">
            @using (Html.BeginForm("PrevPage", "DailyProduct"))
            {
                @Html.Hidden("CategoryKoef", Model.CategoryKoef)
                @Html.Hidden("CompanyKoef", Model.CompanyKoef)
                @Html.Hidden("SaleKoef", Model.SaleKoef)
                @Html.Hidden("Page", Model.Page)
                <input type="submit" class="btn btn-info" value="<" />
            }
        </div>
        <div class="col-lg-1">
            @using (Html.BeginForm("NextPage", "DailyProduct"))
            {
                @Html.Hidden("CategoryKoef", Model.CategoryKoef)
                @Html.Hidden("CompanyKoef", Model.CompanyKoef)
                @Html.Hidden("SaleKoef", Model.SaleKoef)
                @Html.Hidden("Page", Model.Page)
                <input type="submit" class="btn btn-info" value=">" />
            }
        </div>
    </div>
</div>

Faradise.Design.Admin/Views/DailyProduct/PreviousList.cshtml
@model DailyProductModel[]

@{
    ViewData["Title"] = "Прошлые товары дня";
}

<div class="container-fluid">

    <div class="row border rounded vertical-align m-2 p-2">
        <div class="col-lg-1">
            Время установки
        </div>
        <div class="col-lg-2">
            Фото
        </div>

        <div class="col-lg-1">
            ID
        </div>

        <div class="col-lg-2">
            Имя
        </div>

        <div class="col-lg-1">
            Цена
        </div>
        <div class="col-lg-1">
            Скидки
        </div>
        <div class="col-lg-1">
            Старая
        </div>

        <div class="col-lg-1">
            Партнёр
        </div>
        <div class="col-lg-1">
            Ссылка
        </div>
    </div>

    @foreach (var m in Model)
    {
        <div class="row border rounded vertical-align m-1 p-2">

            <div class="col-lg-1">
                @m.OfferTime.AddHours(3).ToString("dd.MM.yy HH:mm")
            </div>

            <div class="col-lg-2 text-center">
                <img src="@m.Product.PhotoUrl" width="180px" />
            </div>

            <div class="col-lg-1">
                ID: @Html.ActionLink(m.Product.Id.ToString(), "ImagesPriority", "Product", new { id = m.Product.Id })
            </div>

            <div class="col-lg-2">
                @m.Product.Name
            </div>

            <div class="col-lg-1">
                @m.Product.Price
            </div>
            <div class="col-lg-1">
                @if (m.Product.PreviousPrice.HasValue)
                {
                    <span>@((int)(100 - @m.Product.Price * 100.0f / @m.Product.PreviousPrice))%</span>
                } else { <span>0%</span> }
            </div>
            <div class="col-lg-1">
                @m.Product.PreviousPrice
            </div>

            <div class="col-lg-1">
                @m.Product.CompanyName
            </div>

            <div class="col-lg-1">
                <a href="https://faradise.ru/product/@m.Product.Id">Ссылка на товар</a>
            </div>
        </div>
    }
</div>